"""Add banner_image to characters

Revision ID: 13482d8b320f
Revises: fe91bb5f6dd0
Create Date: 2026-02-13 11:59:03.518051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13482d8b320f'
down_revision: Union[str, Sequence[str], None] = 'fe91bb5f6dd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweaknow_characters', sa.Column('banner_image', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tweaknow_characters', 'banner_image')
    # ### end Alembic commands ###
