"""Add images to tweaks

Revision ID: 673dd7e26c48
Revises: 2f950d03b3e0
Create Date: 2026-02-04 16:47:29.017395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '673dd7e26c48'
down_revision: Union[str, Sequence[str], None] = '2f950d03b3e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweaks', sa.Column('images', postgresql.ARRAY(sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tweaks', 'images')
    # ### end Alembic commands ###
