"""add trends table

Revision ID: 6babd9dfc2de
Revises: 7de6197dde26
Create Date: 2026-02-21 18:22:02.824595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6babd9dfc2de'
down_revision: Union[str, Sequence[str], None] = '7de6197dde26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('universe_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tweet_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['universe_id'], ['universes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trends_id'), 'trends', ['id'], unique=False)
    op.drop_constraint(op.f('tweaks_retweet_of_id_fkey'), 'tweaks', type_='foreignkey')
    op.drop_column('tweaks', 'retweet_of_id')
    op.drop_column('tweaks', 'is_retweet')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweaks', sa.Column('is_retweet', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('tweaks', sa.Column('retweet_of_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('tweaks_retweet_of_id_fkey'), 'tweaks', 'tweaks', ['retweet_of_id'], ['id'])
    op.drop_index(op.f('ix_trends_id'), table_name='trends')
    op.drop_table('trends')
    # ### end Alembic commands ###
