"""add retweet and quote fields

Revision ID: 7de6197dde26
Revises: 3c4faa8e6b43
Create Date: 2026-02-17 20:55:05.729789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7de6197dde26'
down_revision: Union[str, Sequence[str], None] = '3c4faa8e6b43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweaks', sa.Column('quoted_tweak_id', sa.Integer(), nullable=True))
    op.add_column('tweaks', sa.Column('retweet_of_id', sa.Integer(), nullable=True))
    op.add_column('tweaks', sa.Column('is_retweet', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'tweaks', 'tweaks', ['retweet_of_id'], ['id'])
    op.create_foreign_key(None, 'tweaks', 'tweaks', ['quoted_tweak_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tweaks', type_='foreignkey')
    op.drop_constraint(None, 'tweaks', type_='foreignkey')
    op.drop_column('tweaks', 'is_retweet')
    op.drop_column('tweaks', 'retweet_of_id')
    op.drop_column('tweaks', 'quoted_tweak_id')
    # ### end Alembic commands ###
