"""Add character follows

Revision ID: 86506226152c
Revises: 673dd7e26c48
Create Date: 2026-02-06 11:19:55.258967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86506226152c'
down_revision: Union[str, Sequence[str], None] = '673dd7e26c48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_follows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('following_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['tweaknow_characters.id'], ),
    sa.ForeignKeyConstraint(['following_id'], ['tweaknow_characters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'following_id', name='unique_follow')
    )
    op.create_index(op.f('ix_character_follows_id'), 'character_follows', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_character_follows_id'), table_name='character_follows')
    op.drop_table('character_follows')
    # ### end Alembic commands ###
