"""Add banner and follower display counts

Revision ID: ee72d344d5c3
Revises: 13482d8b320f
Create Date: 2026-02-13 13:54:17.487253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee72d344d5c3'
down_revision: Union[str, Sequence[str], None] = '13482d8b320f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweaknow_characters', sa.Column('display_followers_count', sa.Integer(), nullable=True))
    op.add_column('tweaknow_characters', sa.Column('display_following_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tweaknow_characters', 'display_following_count')
    op.drop_column('tweaknow_characters', 'display_followers_count')
    # ### end Alembic commands ###
