"""add header_image header_text to trends

Revision ID: f833cac79b19
Revises: 6babd9dfc2de
Create Date: 2026-02-22 02:26:11.230975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f833cac79b19'
down_revision: Union[str, Sequence[str], None] = '6babd9dfc2de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trends', sa.Column('header_image', sa.Text(), nullable=True))
    op.add_column('trends', sa.Column('header_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trends', 'header_text')
    op.drop_column('trends', 'header_image')
    # ### end Alembic commands ###
