"""Add reply_to_tweak_id to tweaks

Revision ID: fe91bb5f6dd0
Revises: 86506226152c
Create Date: 2026-02-08 21:57:48.591089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe91bb5f6dd0'
down_revision: Union[str, Sequence[str], None] = '86506226152c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
